name: 🧪 SysScope CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 📦 Abhängigkeiten installieren
        run: |
         python -m pip install --upgrade pip
         pip install psutil colorama

      - name: 📦 weitere Abhängigkeiten
        run: |
         python -m pip install --upgrade pip
         pip install wheel setuptools    

      - name: 🚦 Syntax & Installation testen
        run: |
         pip install dist/*.whl  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Tool testweise ausführen (ohne Root)
        run: |
         python SysScope.py || echo "Erwartete Root-Funktionalität kann im CI übersprungen werden"

      - name: ✅ Testlauf (Basic Check)
        run: |
         python SysScope.py || echo "CI Umgebung: Ignoriere Runtime-Checks, die Root benötigen."

      - name: Lint with Flake8
        run: |
          pip install flake8
          flake8 . --ignore=E501,W503 --max-line-length=127 --statistics
